### ISSUE TITLE
ImportError: cannot import name ‘OrderedDict‘ from ‘typing‘

### ISSUE THREAD

**Issue by Ronchy2000** [Jai-wei/YOLOv8-PySide6-GUI#1]
clone后发现，当python版本低于3.8(我使用的是3.7),报ImportError: cannot import name ‘OrderedDict‘ from ‘typing‘错误。

解决方法：
maxvit.py中
将
`from typing import Any, Callable, List, Optional, OrderedDict，Sequence, Tuple`

变为
```
from typing import Any, Callable, List, Optional, Sequence, Tuple
from typing_extensions import OrderedDict
```

可以解决该问题。

**Comment by Jai-wei** [comment]
学弟牛的😎😎

**Comment by ascacdsaa** [comment]
谢谢，你的帮助很有用
