### ISSUE TITLE
Doesn't work with custom model

### ISSUE THREAD

**Issue by antonmkr** [Jai-wei/YOLOv8-PySide6-GUI#11]
Doesn't work with my custom trained weight
Can anyone help me?

Error:
![Screenshot 2023-08-01 143337](https://github.com/Jai-wei/YOLOv8-PySide6-GUI/assets/120810851/ce9a15e1-d70e-4c1b-8989-0a0843ec98df)

Ultralytics YOLOv8.0.48  Python-3.11.2 torch-2.0.1+cpu CPU
WARNING  ./models/last.pt appears to require 'models.yolo', which is not in ultralytics requirements.
AutoInstall will run now for 'models.yolo' but this feature will be removed in the future.
Recommend fixes are to train a new model using the latest 'ultralytics' package or to run a command with an official YOLOv8 model, i.e. 'yolo predict model=yolov8n.pt'
requirements: YOLOv8 requirement "models.yolo" not found, attempting AutoUpdate...
ERROR: Could not find a version that satisfies the requirement models.yolo (from versions: none)
ERROR: No matching distribution found for models.yolo
No module named 'models.yolo'
requirements:  Command 'pip install "models.yolo"  ' returned non-zero exit status 1.
![Screenshot 2023-08-01 202743](https://github.com/Jai-wei/YOLOv8-PySide6-GUI/assets/120810851/d5836e24-71f8-4550-9dc6-52103a24a561)
What does it mean?

**Comment by lanjunb** [comment]
> Doesn't work with my custom trained weight Can anyone help me?
> 
> Error: ![Screenshot 2023-08-01 143337](https://user-images.githubusercontent.com/120810851/257501895-ce9a15e1-d70e-4c1b-8989-0a0843ec98df.png)
> 
> Ultralytics YOLOv8.0.48 Python-3.11.2 torch-2.0.1+cpu CPU WARNING ./models/last.pt appears to require 'models.yolo', which is not in ultralytics requirements. AutoInstall will run now for 'models.yolo' but this feature will be removed in the future. Recommend fixes are to train a new model using the latest 'ultralytics' package or to run a command with an official YOLOv8 model, i.e. 'yolo predict model=yolov8n.pt' requirements: YOLOv8 requirement "models.yolo" not found, attempting AutoUpdate... ERROR: Could not find a version that satisfies the requirement models.yolo (from versions: none) ERROR: No matching distribution found for models.yolo No module named 'models.yolo' requirements: Command 'pip install "models.yolo" ' returned non-zero exit status 1. ![Screenshot 2023-08-01 202743](https://user-images.githubusercontent.com/120810851/257594934-d5836e24-71f8-4550-9dc6-52103a24a561.png) What does it mean?

It may be that your training model version is too high, you can try to use the Ultralytics version (8.0.48) in this project for training

**Comment by antonmkr** [comment]
> > Doesn't work with my custom trained weight Can anyone help me?
> > Error: ![Screenshot 2023-08-01 143337](https://user-images.githubusercontent.com/120810851/257501895-ce9a15e1-d70e-4c1b-8989-0a0843ec98df.png)
> > Ultralytics YOLOv8.0.48 Python-3.11.2 torch-2.0.1+cpu CPU WARNING ./models/last.pt appears to require 'models.yolo', which is not in ultralytics requirements. AutoInstall will run now for 'models.yolo' but this feature will be removed in the future. Recommend fixes are to train a new model using the latest 'ultralytics' package or to run a command with an official YOLOv8 model, i.e. 'yolo predict model=yolov8n.pt' requirements: YOLOv8 requirement "models.yolo" not found, attempting AutoUpdate... ERROR: Could not find a version that satisfies the requirement models.yolo (from versions: none) ERROR: No matching distribution found for models.yolo No module named 'models.yolo' requirements: Command 'pip install "models.yolo" ' returned non-zero exit status 1. ![Screenshot 2023-08-01 202743](https://user-images.githubusercontent.com/120810851/257594934-d5836e24-71f8-4550-9dc6-52103a24a561.png) What does it mean?
> 
> It may be that your training model version is too high, you can try to use the Ultralytics version (8.0.48) in this project for training

I trained my model with this version and now I get this error. Can you help me please?
![Screenshot 2023-08-07 145121](https://github.com/Jai-wei/YOLOv8-PySide6-GUI/assets/120810851/f2bf58aa-7cbc-487f-b1f7-ad6ad71bde1f)
