### ISSUE TITLE
怎么用segmentation的模型去跑会出错

### ISSUE THREAD

**Issue by Skymc7** [Jai-wei/YOLOv8-PySide6-GUI#2]
具体定位是在main.py里的 def write_results(self, idx, results, batch)

**Comment by Skymc7** [comment]
> 目前仅支持目标检测，有时间会继续实现分割
好嘞，谢谢！大神加油！

**Comment by ascacdsaa** [comment]
> 我这里完成了分割的代码，但是我还不会用github代码上来，哈哈，咔搞

请问可以分享一下吗，我愿意有偿购买，联系qq：942377281

**Comment by Jai-wei** [comment]
> 我这里完成了分割的代码，但是我还不会用github传代码上来，哈哈哈，咋弄

Good job. 最近比较忙，回复不及时，见谅。如果您希望将分割的实现代码开源的话，可以点击`Star`左边的`Fork`按钮，建立一个branch位于您个人账号下。进而提交一个Pr。推荐您访问[该视频](https://www.bilibili.com/video/BV1s3411g7PS/?spm_id_from=333.337.search-card.all.click&vd_source=0940bf29b38efba56ccfc6a3cef8182d)获取等更详细的演示。这只是一个案例，您可以自行查找更多有关GitHub使用的教学资料。

**Comment by s1030512149** [comment]
> > 我这里完成了分割的代码，但是我还不会用github传代码上来，哈哈哈，咋弄
> 
> Good job. 最近比较忙，回复不及时，见谅。如果您希望将分割的实现代码开源的话，可以点击`Star`左边的`Fork`按钮，建立一个branch位于您个人账号下。进而提交一个Pr。推荐您访问[该视频](https://www.bilibili.com/video/BV1s3411g7PS/?spm_id_from=333.337.search-card.all.click&vd_source=0940bf29b38efba56ccfc6a3cef8182d)获取等更详细的演示。这只是一个案例，您可以自行查找更多有关GitHub使用的教学资料。

好像上传完成了，不知道是否可用

**Comment by Jai-wei** [comment]
> > > 我这里完成了分割的代码，但是我还不会用github传代码上来，哈哈哈，咋弄
> > 
> > 
> > Good job. 最近比较忙，回复不及时，见谅。如果您希望将分割的实现代码开源的话，可以点击`Star`左边的`Fork`按钮，建立一个branch位于您个人账号下。进而提交一个Pr。推荐您访问[该视频](https://www.bilibili.com/video/BV1s3411g7PS/?spm_id_from=333.337.search-card.all.click&vd_source=0940bf29b38efba56ccfc6a3cef8182d)获取等更详细的演示。这只是一个案例，您可以自行查找更多有关GitHub使用的教学资料。
> 
> 好像上传完成了，不知道是否可用

未收到任何PR提交呢
